# Welcome to Serverless!
#

service: products-api
# app and org for use with dashboard.serverless.com

frameworkVersion: '>=4.0.0'  

provider:
  name: aws
  runtime: nodejs20.x
  lambdaHashingVersion: 20201221

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "dynamodb:PutItem"
            - "dynamodb:GetItem"
            - "dynamodb:DeleteItem"
            - "dynamodb:Scan"
          Resource:
            - { "Fn::GetAtt": ["ProductsTable", "Arn"] }
            
functions:
  health:
    handler: src/handlers.health
    events:
      - httpApi:
          path: /health
          method: post
  upload_package:
    handler: src/handlers.upload_package
    events:
      - httpApi:
          path: /package
          method: post
  get_rating:
    handler: src/handlers.get_rating
    events:
      - httpApi:
          path: /package/{id}
          method: get
  # update_package:
  #   handler: src/handlers.update_package
  #   events:
  #     - httpApi:
  #         path: /package
  #         method: PUT

# you can add CloudFormation resource templates here
resources:
  Resources:
    ProductsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Packages
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        AttributeDefinitions:
          - AttributeName: productID
            AttributeType: S
        KeySchema:
          - AttributeName: productID
            KeyType: HASH