# Welcome to Serverless!
#

service: products-api
# app and org for use with dashboard.serverless.com

frameworkVersion: '4.4.7'  


provider:
  name: aws
  runtime: nodejs20.x
  lambdaHashingVersion: 20201221
  environment:
    GITHUB_TOKEN: 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

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "dynamodb:PutItem"
            - "dynamodb:GetItem"
            - "dynamodb:DeleteItem"
            - "dynamodb:Scan"
          Resource:
            - { "Fn::GetAtt": ["ProductsTable", "Arn"] }

            
functions:
  health:
    handler: src/handlers.health
    events:
      - httpApi:
          path: /health
          method: post
  upload_package:
    handler: src/handlers.upload_package
    events:
      - httpApi:
          path: /package
          method: post
  get_rating:
    handler:  src/handlers.get_rating
    events:
      - httpApi:
          path: /package/{id}/rate
          method: get
  get_package:
    handler:  src/download.get_package
    events:
      - httpApi:
          path: /package/{id}
          method: get
  download_package:
    handler: src/download.download_package
    events:
      - httpApi:
          path: /package/download
          method: post


# you can add CloudFormation resource templates here
resources:
  Resources:
    ProductsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: PackagesTable
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        AttributeDefinitions:
          - AttributeName: packageName
            AttributeType: S
          - AttributeName: version
            AttributeType: S
        KeySchema:
          - AttributeName: packageName
            KeyType: HASH
          - AttributeName: version
            KeyType: RANGE