name: Project CI/CD

on: 
  push:
  pull_request:

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Serverless Framework
        run: |
          npm install -g serverless
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: "AKIAQ6HIYJ76AI6KVVTY"
          aws-secret-access-key: "MugwOTjFpcVkjUpO4P0MfNaFm69d/Dp9pdSyOT9d"
          aws-region: us-east-1  # Adjust based on your AWS region

      - name: Deploy with Serverless
        env:
          SERVERLESS_ACCESS_KEY: "AKZZBuUhiG65YgNACJk7PoSHds2ld5qOVKlIoZoSS8Dju"
        run: |
          cd backend/products-api
          serverless deploy
        
