name: Project CI/CD

on: 
  push:
    branches: [main]
  pull_request:

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '22.x'
      - name: Run Install
        run: npm install
